[package]
name = "tx-query2-enclave-app"
version = "0.6.0"
authors = ["Crypto.com <chain@crypto.com>"]
edition = "2018"

[dependencies]

[target.'cfg(target_env = "sgx")'.dependencies]
env_logger = { version = "0.7", default-features = false }
log = "0.4"
parity-scale-codec = "1.3"
rand = "0.7"
rs-libc = "0.2"
rustls = "0.18"
secp256k1 = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "535790e91fac1b3b00c770cb339a06feadc5f48d", features = ["lowmemory"] }
thread-pool = "0.1"
zeroize = "1.1"

chain-core = { path = "../../../chain-core", default-features = false, features = ["edp"] }
enclave-protocol = { path = "../../../enclave-protocol", features = ["edp"] }
enclave-utils = { path = "../../../chain-tx-enclave-next/enclave-utils", features = ["sgxstd"] }
ra-enclave = { path = "../../../chain-tx-enclave-next/enclave-ra/ra-enclave" }

# [patch.crates-io]
# ring = { git = "https://github.com/crypto-com/ring.git", rev = "4e1862fb0df9efaf2d2c1ec8cacb1e53104f3daa" }
